engines:
  eslint:
    enabled: true
  stylelint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - calls/**
  - public/js/*
  - test/**
  - views/**
  - routes/**
exclude_paths:
- doc/**
- data/**
- drivers/**
- public/image/*
