engines:
  rubocop:
    enabled: true
  golint:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
ratings:
  paths:
  - calls/**
  - public/**
  - test/**
  - views/**
  - routes/**
exclude_paths:
- doc/**/
- data/**
- ./*.js
- ./routes/phone.js
- ./test/phone_test.js
- ./calls/phone_general.js