engines:
  eslint:
    enabled: true
  stylelint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - client/js/*.js
  - client/stylesheets/*.css
  - server/**/*.js
  - test/**/*.js
  
exclude_paths:
- config/
- client/js/js_libs
- client/stylesheets/libs
- dist/
- doc/
- drivers/
- server/data/


