engines:
  eslint:
    enabled: true
  stylelint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - client/js_es6
  - client/stylesheets
  - server/lib/
  - server/routes/
exclude_paths:
- config/
- doc/
- drivers/
- server/data/
- build/
- client/emissary/
