engines:
  rubocop:
    enabled: false
  golint:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
ratings:
  paths:
  - calls/**
  - public/**
  - views/**
  - routes/**
exclude_paths:
- doc/**/
