engines:
  eslint:
    enabled: true
  stylelint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - client/js/*.js
  - client/stylesheets/*.css
  - server/lib/
  - server/routes/
exclude_paths:
- client/stylesheets/libs
- config/
- dist/
- doc/
- drivers/
- js/js_libs/
- server/data/


