engines:
  eslint:
    enabled: true
  stylelint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - calls/**
  - public/**
  - test/**
  - views/**
  - routes/**
exclude_paths:
- doc/**/
- data/**
- drivers/**
- *.json
- *.png
