'use strict';
let mongoose = require('mongoose');
let Schema = mongoose.Schema;

/** MongoDB Schema for Payment
 * @memberOf Schema
 * @typedef {PaymentSchema} Payment
 * @property {String} company_id - company's id for which the payment is for
 * @property {String} email - email as shown on stripe window
 * @property {Date} paid_time - time of the payment
 * @property {Number} amount - amount paid in USD
 * @property {String} token - stripeToken of the person making the payment
 * #property {String} customer_id - customer id generated by strip
 * @property {String} desc - desc for the payment info (such as month paying for)
 */
let paymentSchema = new Schema({
    company_id: {type: Schema.Types.ObjectId, ref: 'Company',
        index: true, required: true},
    email: {type: String, required: true},
    paid_time: {type: Date, required: true, default: Date.now()},
    amount: {type: Number, required: true},
    token: {type: String, index: true, required: true},
    desc: {type: String, required: true},
}, {versionKey: false});

module.exports = mongoose.model('Payment', paymentSchema);
